# Generated by Django 2.2.5 on 2019-09-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_name', models.CharField(max_length=200)),
                ('tutorial_roll', models.IntegerField()),
                ('tutorial_DOB', models.DateTimeField()),
            ],
        ),
    ]
