# Generated by Django 2.2.5 on 2019-09-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_DOB',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
