# Generated by Django 2.2.5 on 2019-09-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20190908_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tutorial',
        ),
    ]
